### YamlMime:ManagedReference
items:
- uid: KWiJisho.Modules.ConfigJson.Color
  commentId: T:KWiJisho.Modules.ConfigJson.Color
  id: ConfigJson.Color
  parent: KWiJisho.Modules
  children:
  - KWiJisho.Modules.ConfigJson.Color.Blue
  - KWiJisho.Modules.ConfigJson.Color.DiscordColor
  - KWiJisho.Modules.ConfigJson.Color.Green
  - KWiJisho.Modules.ConfigJson.Color.Red
  langs:
  - csharp
  - vb
  name: ConfigJson.Color
  nameWithType: ConfigJson.Color
  fullName: KWiJisho.Modules.ConfigJson.Color
  type: Class
  source:
    remote:
      path: src/KWiJisho/Modules/ConfigJson.cs
      branch: main
      repo: https://github.com/monambike/kwijisho-discord-bot.git
    id: Color
    path: ../src/KWiJisho/Modules/ConfigJson.cs
    startLine: 107
  assemblies:
  - KWIJisho
  namespace: KWiJisho.Modules
  syntax:
    content: internal class ConfigJson.Color
    content.vb: Friend Class ConfigJson.Color
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: KWiJisho.Modules.ConfigJson.Color.Red
  commentId: P:KWiJisho.Modules.ConfigJson.Color.Red
  id: Red
  parent: KWiJisho.Modules.ConfigJson.Color
  langs:
  - csharp
  - vb
  name: Red
  nameWithType: ConfigJson.Color.Red
  fullName: KWiJisho.Modules.ConfigJson.Color.Red
  type: Property
  source:
    remote:
      path: src/KWiJisho/Modules/ConfigJson.cs
      branch: main
      repo: https://github.com/monambike/kwijisho-discord-bot.git
    id: Red
    path: ../src/KWiJisho/Modules/ConfigJson.cs
    startLine: 109
  assemblies:
  - KWIJisho
  namespace: KWiJisho.Modules
  syntax:
    content: >-
      [JsonProperty("red")]

      internal byte Red { get; set; }
    parameters: []
    return:
      type: System.Byte
    content.vb: >-
      <JsonProperty("red")>

      Friend Property Red As Byte
  overload: KWiJisho.Modules.ConfigJson.Color.Red*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: red
- uid: KWiJisho.Modules.ConfigJson.Color.Green
  commentId: P:KWiJisho.Modules.ConfigJson.Color.Green
  id: Green
  parent: KWiJisho.Modules.ConfigJson.Color
  langs:
  - csharp
  - vb
  name: Green
  nameWithType: ConfigJson.Color.Green
  fullName: KWiJisho.Modules.ConfigJson.Color.Green
  type: Property
  source:
    remote:
      path: src/KWiJisho/Modules/ConfigJson.cs
      branch: main
      repo: https://github.com/monambike/kwijisho-discord-bot.git
    id: Green
    path: ../src/KWiJisho/Modules/ConfigJson.cs
    startLine: 112
  assemblies:
  - KWIJisho
  namespace: KWiJisho.Modules
  syntax:
    content: >-
      [JsonProperty("green")]

      internal byte Green { get; set; }
    parameters: []
    return:
      type: System.Byte
    content.vb: >-
      <JsonProperty("green")>

      Friend Property Green As Byte
  overload: KWiJisho.Modules.ConfigJson.Color.Green*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: green
- uid: KWiJisho.Modules.ConfigJson.Color.Blue
  commentId: P:KWiJisho.Modules.ConfigJson.Color.Blue
  id: Blue
  parent: KWiJisho.Modules.ConfigJson.Color
  langs:
  - csharp
  - vb
  name: Blue
  nameWithType: ConfigJson.Color.Blue
  fullName: KWiJisho.Modules.ConfigJson.Color.Blue
  type: Property
  source:
    remote:
      path: src/KWiJisho/Modules/ConfigJson.cs
      branch: main
      repo: https://github.com/monambike/kwijisho-discord-bot.git
    id: Blue
    path: ../src/KWiJisho/Modules/ConfigJson.cs
    startLine: 115
  assemblies:
  - KWIJisho
  namespace: KWiJisho.Modules
  syntax:
    content: >-
      [JsonProperty("blue")]

      internal byte Blue { get; set; }
    parameters: []
    return:
      type: System.Byte
    content.vb: >-
      <JsonProperty("blue")>

      Friend Property Blue As Byte
  overload: KWiJisho.Modules.ConfigJson.Color.Blue*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: blue
- uid: KWiJisho.Modules.ConfigJson.Color.DiscordColor
  commentId: P:KWiJisho.Modules.ConfigJson.Color.DiscordColor
  id: DiscordColor
  parent: KWiJisho.Modules.ConfigJson.Color
  langs:
  - csharp
  - vb
  name: DiscordColor
  nameWithType: ConfigJson.Color.DiscordColor
  fullName: KWiJisho.Modules.ConfigJson.Color.DiscordColor
  type: Property
  source:
    remote:
      path: src/KWiJisho/Modules/ConfigJson.cs
      branch: main
      repo: https://github.com/monambike/kwijisho-discord-bot.git
    id: DiscordColor
    path: ../src/KWiJisho/Modules/ConfigJson.cs
    startLine: 118
  assemblies:
  - KWIJisho
  namespace: KWiJisho.Modules
  syntax:
    content: internal DiscordColor DiscordColor { get; }
    parameters: []
    return:
      type: DSharpPlus.Entities.DiscordColor
    content.vb: Friend ReadOnly Property DiscordColor As DiscordColor
  overload: KWiJisho.Modules.ConfigJson.Color.DiscordColor*
references:
- uid: KWiJisho.Modules
  commentId: N:KWiJisho.Modules
  href: KWiJisho.html
  name: KWiJisho.Modules
  nameWithType: KWiJisho.Modules
  fullName: KWiJisho.Modules
  spec.csharp:
  - uid: KWiJisho
    name: KWiJisho
    href: KWiJisho.html
  - name: .
  - uid: KWiJisho.Modules
    name: Modules
    href: KWiJisho.Modules.html
  spec.vb:
  - uid: KWiJisho
    name: KWiJisho
    href: KWiJisho.html
  - name: .
  - uid: KWiJisho.Modules
    name: Modules
    href: KWiJisho.Modules.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: KWiJisho.Modules.ConfigJson.Color.Red*
  commentId: Overload:KWiJisho.Modules.ConfigJson.Color.Red
  href: KWiJisho.Modules.ConfigJson.Color.html#KWiJisho_Modules_ConfigJson_Color_Red
  name: Red
  nameWithType: ConfigJson.Color.Red
  fullName: KWiJisho.Modules.ConfigJson.Color.Red
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: KWiJisho.Modules.ConfigJson.Color.Green*
  commentId: Overload:KWiJisho.Modules.ConfigJson.Color.Green
  href: KWiJisho.Modules.ConfigJson.Color.html#KWiJisho_Modules_ConfigJson_Color_Green
  name: Green
  nameWithType: ConfigJson.Color.Green
  fullName: KWiJisho.Modules.ConfigJson.Color.Green
- uid: KWiJisho.Modules.ConfigJson.Color.Blue*
  commentId: Overload:KWiJisho.Modules.ConfigJson.Color.Blue
  href: KWiJisho.Modules.ConfigJson.Color.html#KWiJisho_Modules_ConfigJson_Color_Blue
  name: Blue
  nameWithType: ConfigJson.Color.Blue
  fullName: KWiJisho.Modules.ConfigJson.Color.Blue
- uid: KWiJisho.Modules.ConfigJson.Color.DiscordColor*
  commentId: Overload:KWiJisho.Modules.ConfigJson.Color.DiscordColor
  href: KWiJisho.Modules.ConfigJson.Color.html#KWiJisho_Modules_ConfigJson_Color_DiscordColor
  name: DiscordColor
  nameWithType: ConfigJson.Color.DiscordColor
  fullName: KWiJisho.Modules.ConfigJson.Color.DiscordColor
- uid: DSharpPlus.Entities.DiscordColor
  commentId: T:DSharpPlus.Entities.DiscordColor
  parent: DSharpPlus.Entities
  isExternal: true
  name: DiscordColor
  nameWithType: DiscordColor
  fullName: DSharpPlus.Entities.DiscordColor
- uid: DSharpPlus.Entities
  commentId: N:DSharpPlus.Entities
  isExternal: true
  name: DSharpPlus.Entities
  nameWithType: DSharpPlus.Entities
  fullName: DSharpPlus.Entities
  spec.csharp:
  - uid: DSharpPlus
    name: DSharpPlus
    isExternal: true
  - name: .
  - uid: DSharpPlus.Entities
    name: Entities
    isExternal: true
  spec.vb:
  - uid: DSharpPlus
    name: DSharpPlus
    isExternal: true
  - name: .
  - uid: DSharpPlus.Entities
    name: Entities
    isExternal: true
